dashboard/urls.py
from django.urls import path

from .views import index, ContactsListView, PhoneCreateView, PhoneUpdateView, delete_phone, EmailCreateView, \
    EmailUpdateView, delete_email, SocialCreateView, SocialUpdateView, delete_media, ParameterCreateView, \
    delete_contact, ParameterUpdateView, ProductListView, CategoryListView, CategoryCreateView, delete_category, \
    SubCategoryCreateView, CategoryOrderView

app_name = 'dashboard'
urlpatterns = [
    # PARAMETERS START
    path('', index, name='index'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),

    # PHONE START
    path('add-phone/', PhoneCreateView.as_view(), name='addphone'),
    path('number-update/<int:pk>/', PhoneUpdateView.as_view(), name='numberupdate'),
    path('delete-phone/<int:phone_id>/', delete_phone, name='deletephone'),
    # PHONE END

    # EMAIL START
    path('add-email/', EmailCreateView.as_view(), name='addemail'),
    path('update-email/<int:pk>/', EmailUpdateView.as_view(), name='updateemail'),
    path('delete-email/<int:email_id>/', delete_email, name='deleteemail'),
    # EMAIL END

    # SOCIAL START
    path('add-media/', SocialCreateView.as_view(), name='addsocial'),
    path('update-media/<int:pk>/', SocialUpdateView.as_view(), name='updatesocial'),
    path('delete-media/<int:social_id>/', delete_media, name='deletemedial'),
    # SOCIAL END

    # CONTACT START
    path('add-contact/', ParameterCreateView.as_view(), name='addcontact'),
    path('parameter-update/<int:pk>/', ParameterUpdateView.as_view(), name='parameterupdate'),
    path('delete-contact/<int:parameter_id>/', delete_contact, name='deletecontact'),
    # CONTACT END
    # PARAMETERS END

    # PRODUCT START
    path('product-list/', ProductListView.as_view(), name='productlist'),
    path('category-list/', CategoryListView.as_view(), name='categorylist'),
    path('create-category/', CategoryCreateView.as_view(), name='createcategory'),
    path('create-sub-category/', SubCategoryCreateView.as_view(), name='createsubcategory'),
    path('delete-category/<int:category_id>/', delete_category, name='deletecategory'),
    path('product/order/', CategoryOrderView.as_view(), name='module_order')

    # PRODUCT END
]

fazilgroup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
]

dashboard/models.py
from django.db import models

# Create your models here.

parameters/models.py
from django.db import models


class Phone(models.Model):
    phone = models.CharField(max_length=60, verbose_name='Telefon')

    def __str__(self):
        return str(self.phone)


class Email(models.Model):
    email = models.EmailField(verbose_name='E-mail')

    def __str__(self):
        return str(self.email)


class Social(models.Model):
    social_name = models.CharField(max_length=60, verbose_name='Şəbəkə adı')
    social_icon = models.CharField(max_length=60, verbose_name='Şəbəkə ikonu')
    social_link = models.URLField(verbose_name='Şəbəkə linki')

    def __str__(self):
        return self.social_name


class Parameters(models.Model):
    address = models.CharField(max_length=250, verbose_name='Ünvan')
    iframe_map = models.CharField(max_length=1500, verbose_name='Google map iframe')
    phone = models.ManyToManyField(Phone, verbose_name='Telefon')
    email = models.ManyToManyField(Email, verbose_name='E-mail')
    social = models.ManyToManyField(Social, verbose_name='Sosial şəbəkə')

    def __str__(self):
        return f"{self.address}"

dashboard/forms.py
from django import forms
from parameters.models import Phone, Email, Social, Parameters
from products.models import Category


# PARAMETERS START
#     PHONE START


class PhoneCreateForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = ('phone',)
        widgets = {
            'phone': forms.TextInput(attrs={'class': 'form-control inputmask', 'data-mask': '(+999) 99 999-99-99'})
        }


#     PHONE END


#     EMAIL START
class EmailCreateForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ('email',)
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'uemail', 'name': 'uemail',
                                            'aria-describedby': 'uemail-error', 'aria-invalid': 'true'})
        }


#    EMAIL START


#     SOCIAL START
class SocialCreateForm(forms.ModelForm):
    class Meta:
        model = Social
        fields = ('social_name', 'social_icon', 'social_link')
        widgets = {
            'social_name': forms.TextInput(attrs={'class': 'form-control'}),
            'social_icon': forms.TextInput(attrs={'class': 'form-control'}),
            'social_link': forms.TextInput(attrs={'class': 'form-control'}),
        }
#     SOCIAL END


#     PARAMETERS START
class ParameterCreateForm(forms.ModelForm):
    phone = forms.ModelMultipleChoiceField(queryset=Phone.objects.all(), widget=forms.CheckboxSelectMultiple)
    email = forms.ModelMultipleChoiceField(queryset=Email.objects.all(), widget=forms.CheckboxSelectMultiple)
    social = forms.ModelMultipleChoiceField(queryset=Social.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Parameters
        fields = ('address', 'iframe_map', 'phone', 'email', 'social')
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'iframe_map': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'phone': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
            'email': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
            'social': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
        }

#     PARAMETERS END

# PARAMETERS END

# PRODUCT AND CATEGORY START


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2 text-primary'}),
        }


class SubCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'parent')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2 text-primary'}),
            'parent': forms.Select(attrs={'class': 'form-control mb-2 text-primary'}),
        }

dashboard/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import View

from dashboard.forms import PhoneCreateForm, EmailCreateForm, SocialCreateForm, ParameterCreateForm, CategoryCreateForm, \
    SubCategoryCreateForm
from parameters.models import Phone, Email, Social, Parameters
from products.models import Product, Category


def index(request):
    return render(request, 'dashboard/index.html')


# PARAMETERS START
class ContactsListView(ListView):
    model = Phone
    template_name = 'dashboard/parameters/contacts.html'
    context_object_name = 'phones'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ContactsListView, self).get_context_data()
        context['emails'] = Email.objects.all()
        context['socials'] = Social.objects.all()
        context['parameters'] = Parameters.objects.all()
        return context


#     PHONE START
class PhoneCreateView(SuccessMessageMixin, CreateView):
    form_class = PhoneCreateForm
    template_name = 'dashboard/parameters/addphone.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Telefon nömrəsi uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(PhoneCreateView, self).get_context_data()
        return context


class PhoneUpdateView(SuccessMessageMixin, UpdateView):
    form_class = PhoneCreateForm
    model = Phone
    template_name = 'dashboard/parameters/updatenum.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Telefon nömrəsi uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(PhoneUpdateView, self).get_context_data()
        return context


def delete_phone(request, phone_id):
    phone = Phone.objects.get(id=phone_id)
    phone.delete()
    messages.success(request, 'Nömrə uğurla silindi!')
    return redirect('dashboard:contacts')


#     PHONE END


#     EMAIL START
class EmailCreateView(SuccessMessageMixin, CreateView):
    form_class = EmailCreateForm
    template_name = 'dashboard/parameters/addemail.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'E-mail ünvan uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(EmailCreateView, self).get_context_data()
        return context


class EmailUpdateView(SuccessMessageMixin, UpdateView):
    form_class = EmailCreateForm
    model = Email
    template_name = 'dashboard/parameters/updateemail.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'E-mail ünvanı uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(EmailUpdateView, self).get_context_data()
        return context


def delete_email(request, email_id):
    email = Email.objects.get(id=email_id)
    email.delete()
    messages.success(request, 'Email uğurla silindi!')
    return redirect('dashboard:contacts')
#     EMAIL END


#     SOCIAL START
class SocialCreateView(SuccessMessageMixin, CreateView):
    form_class = SocialCreateForm
    template_name = 'dashboard/parameters/addsocial.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Media uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(SocialCreateView, self).get_context_data()
        return context


class SocialUpdateView(SuccessMessageMixin, UpdateView):
    form_class = SocialCreateForm
    model = Social
    template_name = 'dashboard/parameters/updatemedia.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Media uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(SocialUpdateView, self).get_context_data()
        return context


def delete_media(request, social_id):
    social = Social.objects.get(id=social_id)
    social.delete()
    messages.success(request, 'Media uğurla silindi!')
    return redirect('dashboard:contacts')
#     SOCIAL END


#     PARAMETERS START
class ParameterCreateView(SuccessMessageMixin, CreateView):
    form_class = ParameterCreateForm
    template_name = 'dashboard/parameters/addcontact.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Əlaqə məlumatları əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(ParameterCreateView, self).get_context_data()
        context['phones'] = Phone.objects.all()
        context['parameters'] = Parameters.objects.all()
        context['emails'] = Email.objects.all()
        context['socials'] = Social.objects.all()
        return context


class ParameterUpdateView(SuccessMessageMixin, UpdateView):
    form_class = ParameterCreateForm
    model = Parameters
    template_name = 'dashboard/parameters/updateparameter.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Əlaqə məlumatları uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(ParameterUpdateView, self).get_context_data()
        return context


def delete_contact(request, parameter_id):
    social = Parameters.objects.get(id=parameter_id)
    social.delete()
    messages.success(request, 'Əlaqə məlumatı uğurla silindi!')
    return redirect('dashboard:contacts')

#     PARAMETERS END

# PARAMETERS END


# PRODUCT AND CATEGORY START

# PRODUCT
class ProductListView(ListView):
    model = Product
    template_name = 'dashboard/product/product-list.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        return context


# CATEGORY
class CategoryListView(ListView):
    model = Category
    template_name = 'dashboard/product/category-list.html'
    context_object_name = 'categories'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data()
        return context


class CategoryCreateView(SuccessMessageMixin, CreateView):
    form_class = CategoryCreateForm
    template_name = 'dashboard/product/create-category.html'
    success_url = reverse_lazy('dashboard:categorylist')
    success_message = 'Kateqoriya uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data()
        return context


class SubCategoryCreateView(SuccessMessageMixin, CreateView):
    form_class = SubCategoryCreateForm
    template_name = 'dashboard/product/create-sub-category.html'
    success_url = reverse_lazy('dashboard:categorylist')
    success_message = 'Alt kateqoriya uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(SubCategoryCreateView, self).get_context_data()
        return context


class CategoryOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):
    def post(self, request):
        for id, order in self.request_json.items():
            Category.objects.filter(id=id).update(order=order)
        return self.render_json_response({'saved': 'OK'})


def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    messages.success(request, 'Kateqoriya uğurla silindi!')
    return redirect('dashboard:category-list')

parameters/views.py
from django.shortcuts import render

# Create your views here.

dashboard/templates/dashboard/parameters/addemail.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <div class="app-main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>E-mail ünvanı</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:contacts' %}">Əlaqə
                                        məlumatları</a></li>
                                    <li class="breadcrumb-item active text-primary" aria-current="page">yeni e-mail</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="text-secondary">Yeni e-mail</h4>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <label class="control-label" for="{{ form.email.id_for_label }}"></label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <button class="btn btn-square btn-success">Əlavə et</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/parameters/addphone.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <div class="app-main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>Telefon nömrəsi</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:contacts' %}">Əlaqə
                                        məlumatları</a></li>
                                    <li class="breadcrumb-item active text-primary" aria-current="page">yeni nömrə</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="text-secondary">Yeni nömrə</h4>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <label for="{{ form.phone.id_for_label }}"></label>
                                        {{ form.phone }}
                                        <span class="font-14 text-muted">(+999) 99 999-99-99</span>
                                    </div>
                                </div>
                                <button class="btn btn-square btn-success">Əlavə et</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/parameters/contacts.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}Telefon{% endblock %}
{% block content %}
    <div class="app-main" id="main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>Əlaqə məlumatları</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>

                                    <li class="breadcrumb-item active text-primary" aria-current="page">Əlaqə
                                        məlumatları
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="card card-statistics">
                        <div class="card-header add-btn">
                            <div class="card-heading">
                                <h4 class="text-secondary">Əlaqə məlumatları</h4>
                            </div>

                            {% with parameters.count as param %}
                                {% if param < 1 %}
                                    <a class="btn btn-square btn-xs btn-success"
                                       href="{% url 'dashboard:addcontact' %}">
                                        Yeni əlaqə
                                    </a>
                                {% endif %}
                            {% endwith %}
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Ünvan</th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for parameter in parameters %}
                                        <tr>
                                            <th scope="row">{{ parameter.address }}</th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:parameterupdate' parameter.pk %}"
                                                   class="btn btn-icon btn-square btn-primary btn-xs"><i
                                                        class="fa fa-pencil"></i></a>
                                            </th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:deletecontact' parameter.pk %}"
                                                   class="btn btn-icon btn-square btn-danger btn-xs" id="sweetalert-08">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-lg-6">
                    <div class="card card-statistics">
                        <div class="card-header add-btn">
                            <div class="card-heading">
                                <h4 class="text-secondary">Telefon nömrələri</h4>
                            </div>
                            <a class="btn btn-square btn-xs btn-success" href="{% url 'dashboard:addphone' %}">Yeni
                                nömrə</a>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Nömrə</th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for phone in phones %}
                                        <tr>
                                            <th scope="row">{{ phone.phone }}</th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:numberupdate' phone.pk %}"
                                                   class="btn btn-icon btn-square btn-primary btn-xs"><i
                                                        class="fa fa-pencil"></i></a>
                                            </th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:deletephone' phone.pk %}"
                                                   class="btn btn-icon btn-square btn-danger btn-xs"><i
                                                        class="fa fa-trash"></i></a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-lg-6">
                    <div class="card card-statistics">
                        <div class="card-header add-btn">
                            <div class="card-heading">
                                <h4 class="text-secondary">E-mail ünvanları</h4>
                            </div>
                            <a class="btn btn-square btn-xs btn-success" href="{% url 'dashboard:addemail' %}">Yeni
                                e-mail</a>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">E-mail</th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for email in emails %}
                                        <tr>
                                            <th scope="row">{{ email.email }}</th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:updateemail' email.pk %}"
                                                   class="btn btn-icon btn-square btn-primary btn-xs"><i
                                                        class="fa fa-pencil"></i></a>
                                            </th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:deleteemail' email.pk %}"
                                                   class="btn btn-icon btn-square btn-danger btn-xs"><i
                                                        class="fa fa-trash"></i></a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-lg-6">
                    <div class="card card-statistics">
                        <div class="card-header add-btn">
                            <div class="card-heading">
                                <h4 class="text-secondary">Sosial media</h4>
                            </div>
                            <a class="btn btn-square btn-xs btn-success" href="{% url 'dashboard:addsocial' %}">Yeni
                                media</a>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Media adı</th>
                                        <th scope="col">Link</th>
                                        <th scope="col">Icon</th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for social in socials %}
                                        <tr>
                                            <th scope="row">{{ social.social_name }}</th>
                                            <th scope="row">{{ social.social_link }}</th>
                                            <th><i class="fa {{ social.social_icon }}"></i></th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:updatesocial' social.pk %}"
                                                   class="btn btn-icon btn-square btn-primary btn-xs">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                            </th>
                                            <th scope="row" class="btn_cell">
                                                <a href="{% url 'dashboard:deletemedial' social.pk %}"
                                                   class="btn btn-icon btn-square btn-danger btn-xs"><i
                                                        class="fa fa-trash"></i></a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}