dashboard/urls.py
from django.urls import path

from .views import index, ContactsListView, PhoneCreateView, PhoneUpdateView, delete_phone, EmailCreateView, \
    EmailUpdateView, delete_email, SocialCreateView, SocialUpdateView, delete_media, ParameterCreateView, \
    delete_contact, ParameterUpdateView, ProductListView, CategoryListView, CategoryCreateView, delete_category, \
    SubCategoryCreateView, CategoryOrderView

app_name = 'dashboard'
urlpatterns = [
    # PARAMETERS START
    path('', index, name='index'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),

    # PHONE START
    path('add-phone/', PhoneCreateView.as_view(), name='addphone'),
    path('number-update/<int:pk>/', PhoneUpdateView.as_view(), name='numberupdate'),
    path('delete-phone/<int:phone_id>/', delete_phone, name='deletephone'),
    # PHONE END

    # EMAIL START
    path('add-email/', EmailCreateView.as_view(), name='addemail'),
    path('update-email/<int:pk>/', EmailUpdateView.as_view(), name='updateemail'),
    path('delete-email/<int:email_id>/', delete_email, name='deleteemail'),
    # EMAIL END

    # SOCIAL START
    path('add-media/', SocialCreateView.as_view(), name='addsocial'),
    path('update-media/<int:pk>/', SocialUpdateView.as_view(), name='updatesocial'),
    path('delete-media/<int:social_id>/', delete_media, name='deletemedial'),
    # SOCIAL END

    # CONTACT START
    path('add-contact/', ParameterCreateView.as_view(), name='addcontact'),
    path('parameter-update/<int:pk>/', ParameterUpdateView.as_view(), name='parameterupdate'),
    path('delete-contact/<int:parameter_id>/', delete_contact, name='deletecontact'),
    # CONTACT END
    # PARAMETERS END

    # PRODUCT START
    path('product-list/', ProductListView.as_view(), name='productlist'),
    path('category-list/', CategoryListView.as_view(), name='categorylist'),
    path('create-category/', CategoryCreateView.as_view(), name='createcategory'),
    path('create-sub-category/', SubCategoryCreateView.as_view(), name='createsubcategory'),
    path('delete-category/<int:category_id>/', delete_category, name='deletecategory'),
    path('product/order/', CategoryOrderView.as_view(), name='module_order')

    # PRODUCT END
]

fazilgroup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
]

dashboard/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils import timezone
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from products.fileds import OrderField


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    order = OrderField(blank=True, for_fields=['parent'])

    def __str__(self):
        return f"{self.name}"

    class MPTTMeta:
        order_insertion_by = ['order']


class Product(models.Model):
    class Status(models.Model):
        choices = None
        DRAFT = 'DF', 'Deaktiv'
        PUBLISH = 'PB', 'Aktiv'

    product_name = models.CharField(max_length=250, verbose_name='Məhsulun adı')
    category = TreeForeignKey(Category, on_delete=models.CASCADE, verbose_name='Məhsulun kateqoriyası')
    slag = models.SlugField(max_length=250, verbose_name='Məhsulun slaqı')
    description = models.TextField(verbose_name='Açıqlama')
    packaging = models.CharField(max_length=250, verbose_name='Qablaşdırma')
    consumption = models.CharField(max_length=250, verbose_name='Sərfiyyat')
    image = models.ImageField(upload_to="image/product/%Y/%m/%d/", null=True, blank=True, verbose_name='Şəkil')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    publish = models.DateTimeField(default=timezone.now, verbose_name='Yerləçdirmə tarixi')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')
    update = models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')

    def __str__(self):
        return f"{self.product_name}"

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

dashboard/forms.py
from django import forms
from parameters.models import Phone, Email, Social, Parameters
from products.models import Category


# PARAMETERS START
#     PHONE START


class PhoneCreateForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = ('phone',)
        widgets = {
            'phone': forms.TextInput(attrs={'class': 'form-control inputmask', 'data-mask': '(+999) 99 999-99-99'})
        }


#     PHONE END


#     EMAIL START
class EmailCreateForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ('email',)
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'uemail', 'name': 'uemail',
                                            'aria-describedby': 'uemail-error', 'aria-invalid': 'true'})
        }


#    EMAIL START


#     SOCIAL START
class SocialCreateForm(forms.ModelForm):
    class Meta:
        model = Social
        fields = ('social_name', 'social_icon', 'social_link')
        widgets = {
            'social_name': forms.TextInput(attrs={'class': 'form-control'}),
            'social_icon': forms.TextInput(attrs={'class': 'form-control'}),
            'social_link': forms.TextInput(attrs={'class': 'form-control'}),
        }
#     SOCIAL END


#     PARAMETERS START
class ParameterCreateForm(forms.ModelForm):
    phone = forms.ModelMultipleChoiceField(queryset=Phone.objects.all(), widget=forms.CheckboxSelectMultiple)
    email = forms.ModelMultipleChoiceField(queryset=Email.objects.all(), widget=forms.CheckboxSelectMultiple)
    social = forms.ModelMultipleChoiceField(queryset=Social.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Parameters
        fields = ('address', 'iframe_map', 'phone', 'email', 'social')
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'iframe_map': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'phone': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
            'email': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
            'social': forms.SelectMultiple(attrs={'class': 'form-control mb-2 text-primary'}),
        }

#     PARAMETERS END

# PARAMETERS END

# PRODUCT AND CATEGORY START


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2 text-primary'}),
        }


class SubCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'parent')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2 text-primary'}),
            'parent': forms.Select(attrs={'class': 'form-control mb-2 text-primary'}),
        }

dashboard/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import View

from dashboard.forms import PhoneCreateForm, EmailCreateForm, SocialCreateForm, ParameterCreateForm, CategoryCreateForm, \
    SubCategoryCreateForm
from parameters.models import Phone, Email, Social, Parameters
from products.models import Product, Category


def index(request):
    return render(request, 'dashboard/index.html')


# PARAMETERS START
class ContactsListView(ListView):
    model = Phone
    template_name = 'dashboard/parameters/contacts.html'
    context_object_name = 'phones'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ContactsListView, self).get_context_data()
        context['emails'] = Email.objects.all()
        context['socials'] = Social.objects.all()
        context['parameters'] = Parameters.objects.all()
        return context


#     PHONE START
class PhoneCreateView(SuccessMessageMixin, CreateView):
    form_class = PhoneCreateForm
    template_name = 'dashboard/parameters/addphone.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Telefon nömrəsi uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(PhoneCreateView, self).get_context_data()
        return context


class PhoneUpdateView(SuccessMessageMixin, UpdateView):
    form_class = PhoneCreateForm
    model = Phone
    template_name = 'dashboard/parameters/updatenum.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Telefon nömrəsi uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(PhoneUpdateView, self).get_context_data()
        return context


def delete_phone(request, phone_id):
    phone = Phone.objects.get(id=phone_id)
    phone.delete()
    messages.success(request, 'Nömrə uğurla silindi!')
    return redirect('dashboard:contacts')


#     PHONE END


#     EMAIL START
class EmailCreateView(SuccessMessageMixin, CreateView):
    form_class = EmailCreateForm
    template_name = 'dashboard/parameters/addemail.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'E-mail ünvan uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(EmailCreateView, self).get_context_data()
        return context


class EmailUpdateView(SuccessMessageMixin, UpdateView):
    form_class = EmailCreateForm
    model = Email
    template_name = 'dashboard/parameters/updateemail.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'E-mail ünvanı uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(EmailUpdateView, self).get_context_data()
        return context


def delete_email(request, email_id):
    email = Email.objects.get(id=email_id)
    email.delete()
    messages.success(request, 'Email uğurla silindi!')
    return redirect('dashboard:contacts')
#     EMAIL END


#     SOCIAL START
class SocialCreateView(SuccessMessageMixin, CreateView):
    form_class = SocialCreateForm
    template_name = 'dashboard/parameters/addsocial.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Media uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(SocialCreateView, self).get_context_data()
        return context


class SocialUpdateView(SuccessMessageMixin, UpdateView):
    form_class = SocialCreateForm
    model = Social
    template_name = 'dashboard/parameters/updatemedia.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Media uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(SocialUpdateView, self).get_context_data()
        return context


def delete_media(request, social_id):
    social = Social.objects.get(id=social_id)
    social.delete()
    messages.success(request, 'Media uğurla silindi!')
    return redirect('dashboard:contacts')
#     SOCIAL END


#     PARAMETERS START
class ParameterCreateView(SuccessMessageMixin, CreateView):
    form_class = ParameterCreateForm
    template_name = 'dashboard/parameters/addcontact.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Əlaqə məlumatları əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(ParameterCreateView, self).get_context_data()
        context['phones'] = Phone.objects.all()
        context['parameters'] = Parameters.objects.all()
        context['emails'] = Email.objects.all()
        context['socials'] = Social.objects.all()
        return context


class ParameterUpdateView(SuccessMessageMixin, UpdateView):
    form_class = ParameterCreateForm
    model = Parameters
    template_name = 'dashboard/parameters/updateparameter.html'
    success_url = reverse_lazy('dashboard:contacts')
    success_message = 'Əlaqə məlumatları uğurla yeniləndi!'

    def get_context_data(self, **kwargs):
        context = super(ParameterUpdateView, self).get_context_data()
        return context


def delete_contact(request, parameter_id):
    social = Parameters.objects.get(id=parameter_id)
    social.delete()
    messages.success(request, 'Əlaqə məlumatı uğurla silindi!')
    return redirect('dashboard:contacts')

#     PARAMETERS END

# PARAMETERS END


# PRODUCT AND CATEGORY START

# PRODUCT
class ProductListView(ListView):
    model = Product
    template_name = 'dashboard/product/product-list.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        return context


# CATEGORY
class CategoryListView(ListView):
    model = Category
    template_name = 'dashboard/product/category-list.html'
    context_object_name = 'categories'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data()
        return context


class CategoryCreateView(SuccessMessageMixin, CreateView):
    form_class = CategoryCreateForm
    template_name = 'dashboard/product/create-category.html'
    success_url = reverse_lazy('dashboard:categorylist')
    success_message = 'Kateqoriya uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data()
        return context


class SubCategoryCreateView(SuccessMessageMixin, CreateView):
    form_class = SubCategoryCreateForm
    template_name = 'dashboard/product/create-sub-category.html'
    success_url = reverse_lazy('dashboard:categorylist')
    success_message = 'Alt kateqoriya uğurla əlavə edildi!'

    def get_context_data(self, **kwargs):
        context = super(SubCategoryCreateView, self).get_context_data()
        return context


class CategoryOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):
    def post(self, request):
        for id, order in self.request_json.items():
            Category.objects.filter(id=id).update(order=order)
        return self.render_json_response({'saved': 'OK'})


def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    messages.success(request, 'Kateqoriya uğurla silindi!')
    return redirect('dashboard:category-list')

products/views.py
from django.shortcuts import render

dashboard/templates/dashboard/product/category-list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="app-main">
    <div class="container-fluid">
        <div class="row">
            {% include 'inc/message.html' %}
            <div class="col-md-12 m-b-30">
                <div class="d-block d-lg-flex flex-nowrap align-items-center">
                    <div class="page-title mr-4 pr-4 border-right">
                        <h3>Kateqoriyalar</h3>
                    </div>
                    <div class="breadcrumb-bar align-items-center">
                        <nav>
                            <ol class="breadcrumb p-0 m-b-0">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                        class="ti ti-home"></i></a></li>
                                <li class="breadcrumb-item active text-primary" aria-current="page">Kateqoriya
                                    siyahısı
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row nestable-contant nestable-wrapper">
                    <div class="col-lg-6">
                        <div class="card card-statistics">
                            <div class="card-header">
                                <a href="{% url 'dashboard:createcategory' %}" class="btn btn-square btn-success">Yeni
                                    kateqoriya</a>
                                <a href="{% url 'dashboard:createsubcategory' %}" class="btn btn-square btn-success">Yeni
                                    alt kateqoriya</a>
                            </div>

                            <div class="card-body">

<!--                                <div class="dd" id="nestable">-->
<!--                                    {% load mptt_tags %}-->
<!--                                    <ol class="dd-list" id="modules">-->
<!--                                        {% recursetree categories %}-->
<!--                                        <li id="{{ node.id }}" class="dd-item dd-collapsed" data-id="{{ node.id }}">-->
<!--                                            <div class="dd-handle order">{{ node.name }}: {{ node.order|add:1 }}</div>-->
<!--                                            {% if not node.is_leaf_node %}-->
<!--                                            <ol class="dd-list order">-->
<!--                                                {{ children }}-->
<!--                                            </ol>-->
<!--                                            {% endif %}-->
<!--                                        </li>-->
<!--                                        {% endrecursetree %}-->
<!--                                    </ol>-->
<!--                                </div>-->
                                <ul id="modules">
                                    {% for category in categories.all %}

                                    <li data-id="{{ category.id }}" {% if m == module %}class="selected"{% endif %}>
                                         Module <span class="order">{{ category.order|add:1 }}</span>
                                        <br>
                                        {{ category.name }}
                                    </li>
                                    {% endfor %}

                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block include_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5sortable/0.13.3/html5sortable.min.js"></script>
{% endblock %}

{% block domready %}
  var options = {
      method: 'POST',
      mode: 'same-origin'
  }

  const moduleOrderUrl = '{% url "dashboard:module_order" %}';

  sortable('#modules', {
    forcePlaceholderSize: true,
    placeholderClass: 'placeholder'
  })[0].addEventListener('sortupdate', function(e) {

    modulesOrder = {};
    var modules = document.querySelectorAll('#modules li');
    modules.forEach(function (node, index) {

      modulesOrder[node.dataset.id] = index;

      node.querySelector('.order').innerHTML = index + 1;

      options['body'] = JSON.stringify(modulesOrder);
      // send HTTP request
        console.log(e.detail);
      fetch(moduleOrderUrl, options)
    });
  });

{% endblock %}

dashboard/templates/dashboard/product/create-category.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <div class="app-main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>Yeni kateqoriya</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:categorylist' %}">Kateqoriyalar</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary" aria-current="page">yeni
                                        kateqoriya
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 justify-content-center">
                    <div class="card card-statistics">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <label class="control-label" for="{{ form.name.id_for_label }}">
                                            Kateqoriya adı
                                        </label>
                                        {{ form.name }}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-square btn-success mt-3">Əlavə et</button>
                            </form>
                        </div>
                    </div>
                </div>CharSet
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/product/create-sub-category.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <div class="app-main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>Yeni kateqoriya</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:categorylist' %}">Kateqoriyalar</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary" aria-current="page">yeni
                                        kateqoriya
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <label class="control-label" for="{{ form.name.id_for_label }}">
                                            Alt kateqoriya adı
                                        </label>
                                        {{ form.name }}
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="control-label" for="{{ form.parent.id_for_label }}">
                                            Kateqoriya adı
                                        </label>
                                        {{ form.parent }}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-square btn-success mt-3">Əlavə et</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/product/product-list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <div class="app-main">
        <div class="container-fluid">
            <div class="row">
                {% include 'inc/message.html' %}
                <div class="col-md-12 m-b-30">
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h3>Məhsullar</h3>
                        </div>
                        <div class="breadcrumb-bar align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i
                                            class="ti ti-home"></i></a></li>
                                    <li class="breadcrumb-item active text-primary" aria-current="page">Məhsula siyahısı
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}